### PR TITLE
Fully working 1.7.x-1.8.x backwards compatibility without client crashes, many project improvements and more!

### PR DESCRIPTION
**Pull request by harrydevane**
Changelog:
- Reverts v1_7_R4 to use integers for ageable as 1.7.10 clients require,
  this was a bad 1.8-only protocol hack change that crashed every 1.7.10
  client and broke all craftbukkit(not spigot) 1.7.10 builds.
- Adds a ProtocolLib listener to fix all crashes/problems for 1.8
  clients on the protocol hack 1.7.x-1.8.x builds. (Only enables if
  ProtocolLib is installed, otherwise warns about possible crashes)
- Fixes a typo in ConfigOptions.
- Moves EntityType and Material enum constants to wrapper classes.
  Before, all backwards compatibility was completely broken due to the
  plugin directly referencing RABBIT etc.
- Improves the MenuListener by reducing inventory map calls, using a
  better match method than equals(), checking if a player clicked and
  removing redundant cancels.
- Adds event priorities/ignore cancelled's to relative events. Improves
  performance greatly on events such as the PlayerMoveEvent.
- Fixes EntityAgeablePet's setBaby method on R_1_7_X.
- Fixes human pets gameprofile reflection being set incorrectly on
  R_1_7_X (fixes a server crash when a human pet is spawned).
- Removes redundant setBaby methods in EntityHorse/EntityVillager.
- Fixes wolf collar color setting.
- Removes the not-used ChunkListener class.
- Changes maven shade patterns to be project-specific.
- Adds dmulloy2's maven repository for ProtocolLib.
- Adds elmakers maven repository since it contains 1.8 craftbukkit
  builds (none of the other repositories do).

The result of this is perfectly working 1.7.X-1.8.X client support on
protocol hack builds. (Supports both versions at the same time!)
All features/changes have been fully tested prior to submitting this
pull request.

### CODE REVIEW

**Comment by CaptainBern** [comment]
Looks good to me.

**Comment by DSH105** [comment]
Only problem is that the CI can't locate `com.comphenix.packetwrapper` in any of the new repositories ([build log](https://ci.dsh105.com/job/EchoPet-PR539/5/console)).

Other than that, awesome :+1:.

**Comment by Harry5573** [comment]
Fixed.

**Comment by DSH105** [comment]
Thanks! :D

**Comment by Brend-Smits** [comment]
Would you perhaps be able to share a build with this Pull Request in it? I'm having trouble booting EchoPets because of the Endermite issue. 

The jenkins seem to be offline. Maybe @harrydevane has a build? Would be much appreciated!

**Pull request merged**
